stages:
  - build

pages:
  stage: build
  script:
    - npm install
    - npx resumed render resume.json --theme eloquent
    - ls
    - sudo mkdir -p ./public
    - sudo mv resume.html ./public/index.html
    - sudo chmod -R +w ./public
  artifacts:
    paths:
      - public
