image: node:latest

stages:
  - build
  - deploy

pages:
  stage: build
  script:
    - npm install
    - npx resumed render resume.json --theme eloquent
    - mkdir public
    - mv resume.html public/index.html
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  script:
    - git config --global user.name "Nom de l'utilisateur"
    - git config --global user.email "adresse-email@example.com"
    - git checkout -B gh-pages
    - git add .
    - git commit -m "Mise à jour du CV"
    - git push -f origin gh-pages
