stages:
  - build

pages:
  stage: build
  script:
    - npm install
    - npx resumed render resume.json --theme eloquent
    - ls
    - mkdir ./public
    - mv resume.html ./public/index.html
    - chmod -R +w ./public # Ajouter cette ligne pour donner des droits en écriture
  artifacts:
    paths:
      - public
